// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmK76Ysv3IOzyQG2CIkU7PayjXBYbZyhQ',
    appId: '1:575736170984:web:56da5664109095c212fc5d',
    messagingSenderId: '575736170984',
    projectId: 'fake-news-9ca6f',
    authDomain: 'fake-news-9ca6f.firebaseapp.com',
    storageBucket: 'fake-news-9ca6f.firebasestorage.app',
    measurementId: 'G-T0K3RWL5T9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1fVN9yMPgObtKVhx07EXQ2HjeLHm_As0',
    appId: '1:575736170984:android:77bfaa32f352cdf812fc5d',
    messagingSenderId: '575736170984',
    projectId: 'fake-news-9ca6f',
    storageBucket: 'fake-news-9ca6f.firebasestorage.app',
  );
}
